import "./style.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-center text-center">
        <nav className="flex justify-between items-center font-bold bg-black text-white p-6 px-32">
          <h1 className="text-cyan-300 font-extrabold font-mono">NextLearn</h1>
          <ul className="flex justify-center items-center text-center list-none gap-8 ">
            <li className="hover:cursor-pointer">Home</li>
            <li className="hover:cursor-pointer">Contact</li>
            <li className="hover:cursor-pointer">About</li>
          </ul>
        </nav>
        <div className="pb-80 pt-10 font-extrabold text-[4re]">{children}</div>
        <footer className="bg-black text-24 p-8 text-white bottom-0">
          @eedrisharuna
        </footer>
      </body>
    </html>
  );
}
